const express = require('express'); //IMPORTANDO O EXPRESS.

const app = express(); // DEFININDO A CONSTANTE 'APP' COMO EXPRESS.


// O GET É ACIONADO QUANDO O USUÁRIO ACESSAR A ROTA PASSADA NO PRIMEIRO PARÂMETRO.
// O REQ SIMBOLIZA A REQUISIÇÃO QUE ESTÁ SENDO FEITA PARA O SERVIDOR. ELE CONTERÁ TODOS OS DETALHES E INFORMAÇÕES DESSA REQUISIÇÃO COMO PARÂMETROS, CORPO DA REQUISIÇÃO, USUÁRIO QUE FEZ A REQUISIÇÃO, ETC.
// O RES SIMBOLIZA A RESPOSTA QUE SERÁ DADA PARA A REQUISIÇÃO.
app.get('/', (req, res) => { 
    res.send('Hello World');
});

app.listen(3001);